### PR TITLE
Support hardware watchdog for Intel Rangeley CPU

### PR DESCRIPTION
**Pull request by Lewis-Kang**

### CODE REVIEW

**Comment by sonoble** [comment]
@jnealtowns any thoughts here?

**Comment by jnealtowns** [comment]
@sonoble  Please regress the change on a 3.2 platform and merge.

**Comment by sonoble** [comment]
Hi Lewis,

I am seeing issues with one of your patches:

Appying driver-mfd-lpc-ich.patch...
patching file drivers/mfd/lpc_ich.c
patching file include/linux/mfd/lpc_ich.h
patching file drivers/mfd/Kconfig
Hunk #1 succeeded at 658 with fuzz 2.
patching file drivers/mfd/Makefile
Hunk #1 FAILED at 91.
1 out of 1 hunk FAILED -- saving rejects to file drivers/mfd/Makefile.rej

 more ./packages/base/amd64/kernels/kernel-3.2-deb7-x86-64-all/builds/linux-3.2.65-1+deb7u2/drivers/mfd/Makefile.rej
--- drivers/mfd/Makefile
+++ drivers/mfd/Makefile
@@ -91,6 +91,7 @@
 obj-$(CONFIG_MFD_TIMBERDALE)    += timberdale.o
 obj-$(CONFIG_PMIC_ADP5520)    += adp5520.o
 obj-$(CONFIG_LPC_SCH)     += lpc_sch.o
+obj-$(CONFIG_LPC_ICH)           += lpc_ich.o
 obj-$(CONFIG_MFD_RDC321X) += rdc321x-southbridge.o
 obj-$(CONFIG_MFD_JANZ_CMODIO) += janz-cmodio.o
 obj-$(CONFIG_MFD_JZ4740_ADC)  += jz4740-adc.o

**Comment by sonoble** [comment]
Hi Again Lewis,

It looks like my patch removed the tabs, so I have redone the patch and it applied.  I will update this shortly if everything works.

**Comment by Lewis-Kang** [comment]
Hi Steven,

Any process on this? Thanks.

**Comment by sonoble** [comment]
Hi Lewis,

I have been running it for a few days without issue, so I will merge it.

**Comment by Lewis-Kang** [comment]
Thanks

**Pull request merged**
