### PR TITLE
SFP control set support for Multi-rate selection supporting transceivers

### PR DESCRIPTION
**Pull request by muthukumars-arrcus**
This PR is raised to add Multi-rate select in sfp control set, for multi-rate supporting transeivers

This is supported as per SFF-8472 : 5.7 Rate Identifier [Address A0h, Byte 13]

Ref : SFF-8472: https://members.snia.org/document/dl/25916

Example : FiniserFTLX8574D3BCV, it supports multimode rates (1G/10G).  https://www.epsglobal.com/Media-Library/EPSGlobal/Products/files/finisar/transceivers/FTLX8574D3BCV.pdf?ext=.pdf

Requesting for review & commet/approve the code change

### CODE REVIEW

**Comment by muthukumars-arrcus** [comment]
@sonoble Requesting for review & commet/approve the code change

**Comment by muthukumars-arrcus** [comment]
@sonoble Please review the file changes and notify us of any comments

**Comment by muthukumars-arrcus** [comment]
Hi @sonoble 
Please note we have also verified the code change with a multi-rate transceiver (https://shop.fiber24.net/mediafiles/datasheets/finisar/FTLX8574D3BCV%20Product%20Spec%20RevB.pdf)

Please let us know if you need any more information.

Requesting for review & commet/approve the code change

Regards
S Muthu Kumar

**Comment by sonoble** [comment]
Are you able to fix the dco? I will try and build/test this later this week.

**Comment by muthukumars-arrcus** [comment]
Hi , I have signed-off all my changes. (see my capture below). But strangely the DCO is not getting cleared. Not sure how to resolve this. Please let me know how to circumvent or resolve this ?

`muthu@localhost:~/10g_mr/OpenNetworkLinux$ git log
commit 2c0efae6ec7c5c3ddca1a430af716854e8fc9860 (HEAD -> 10g_multirate)
Author: S Muthu Kumar <muthukumars@arrcuscom>
Date:   Tue Jun 11 11:11:13 2024 +0000

    editor junk files removed
    
    Signed-off-by: S Muthu Kumar <muthukumars@arrcuscom>

commit 099c65e458906403b30f6dce6795ceef990699a5
Author: S Muthu Kumar <muthukumars@arrcuscom>
Date:   Tue Jun 11 11:00:58 2024 +0000

    ONLP_SFP_SOFT_RATE_CNTRL_FLAG addition
    
    Signed-off-by: S Muthu Kumar <muthukumars@arrcuscom>

commit 746f369a7f82f834f3668e60700dc30d7014ba96
Author: S Muthu Kumar <muthukumars@arrcuscom>
Date:   Wed May 29 07:05:38 2024 +0000

    added SOFT_RATE_SELECT control flag
    
    Signed-off-by: S Muthu Kumar <muthukumars@arrcuscom>

commit b1ba047484bc88940323bc9cd454c68281639d9c
Author: S Muthu Kumar <muthukumars@arrcuscom>
Date:   Tue May 28 09:06:53 2024 +0000

    Code addition in onlp sfp control to support Multi-rate soft select
    
    Signed-off-by: S Muthu Kumar <muthukumars@arrcuscom>

Regards
S Muthu Kumar

**Comment by muthukumars-arrcus** [comment]
closing this pr as unable to resolve the signoff issue. Instead created a new PR : https://github.com/opencomputeproject/OpenNetworkLinux/pull/984

Please use the above PR for further review process

**Pull request closed without merging**
