### PR TITLE
new init.d script to run a script from mnt flash if it exists

### PR DESCRIPTION
**Pull request by sonoble**
If someone creates a script in /mnt/flash called init-script, it will be called on boot.

### CODE REVIEW

**Comment by jnealtowns** [comment]
@sonoble  What is the use case for this change?

**Comment by sonoble** [comment]
Requested by multiple end users as a way to execute scripts on startup that are not lost on reboot.

**Comment by capveg** [comment]
FYI: this is a hack that Steve used for the OCP OOM Demo and I suggested he
make a pull request so we can discuss.

Seems mostly harmless to me and will even be useful once we support a fully
persistent file system because we will still have the current read-only
style SWI.

Thoughts?

- Rob
.

**Comment by jnealtowns** [comment]
Lets hold off on this particular pull request. I'm working on the partition conversion and integrated the early boot.d init stages. When those are done we can add this option in a way that fits into that new workflow.

**Comment by capveg** [comment]
KK.  Let us know when you're done with the refactoring and we'll revisit.

Thanks.

- Rob
.

**Comment by sonoble** [comment]
Testing access

**Comment by bsn-abat** [comment]
One more test

**Pull request closed without merging**
