### PR TITLE
[as7726-32x] Fix use '%' in AIM_LOG string

### PR DESCRIPTION
**Pull request by jostar-yang**
Signed-off-by: Jostar Yang <jostar_yang@accton.com.tw>

### CODE REVIEW

**Comment by jostar-yang** [comment]
Fix as7726, as7326 and  as4630 platform.

**Comment by paulmenzel** [comment]
> [as7726-32x]Fix use '%' in AIM_LOG string

In the merge/pull request description and commit message summary, please add a space after the closing ] to improve legibility.

> Fix as7726, as7326 and as4630 platform.

Should the tag in the descriptions be updated?

Please also describe the problem in the commit message.

It looks like replacing % by the string *percentage* works around some problem in `AIM_LOG`? Can’t you use `%%` to escape the percentage sign?

**Comment by jostar-yang** [comment]
When there is "% speed". AIM_LOG_XXX will think this should has one parameter that need to input. But in fact, no this paramter.
Use "%%" should be ok.  But we use "percentage" is ok after our test.  It can output what we expect string.

**Comment by paulmenzel** [comment]
> When there is "% speed". AIM_LOG_XXX will think this should has one parameter that need to input. But in fact, no this paramter.

Please amend the commit message with `git commit --amend` and add the description there, and (force) push that. (paramter → param*e*ter)

> Use "%%" should be ok. But we use "percentage" is ok after our test. It can output what we expect string.

Reading the error message is now actually incorrect, or at least very uncommon English. The string should be *percent* to my knowledge, but using the unit sign should be preferred.

**Comment by paulmenzel** [comment]
Thank you. Two more nits for the commit message:

1.  The Signed-off-by line should be the last line.
2.  You could improve

    > Use "%%" to instead of "%".
    > Fixed platform include as7726,as4630 and as7326.

    Use `%%` instead of `%`.

    Fixed platforms include as7726, as4630 and as7326.

**Comment by paulmenzel** [comment]
The summary still only contains *[as7726-32x]*. Should that be removed as more platforms are affected, or sholud it be extended?

**Pull request merged**
