### PR TITLE
[Celestica/Silverstonev2]  Add  Silverstonev2 platform

### PR DESCRIPTION
**Pull request by ingridcelestica**
- **CPU**: Intel Hewitt Lake D1627
- **MAC**: Broadcom BCM56980 
- **Network**: 32x10/25/40/100/400G ethernet traffic  ports, 1(or 2) SFP+,1 RJ-45 console serial port, supporting  9600 and 115200 baud and 1 RJ-45 Ethernet management port, capable of supporting 10/100/1000BASE-T Ethernet, support SOL function

Signed-off-by: Nicholas Wu [nicwu@celestica.com](mailto:nicwu@celestica.com)
Signed-off-by: Ingrid Huang [inhuang@celestica.com](mailto:inhuang@celestica.com)
Signed-off-by: Jersey Yang [jerseyyang@celestica.com](mailto:jersyang@celestica.com)
Signed-off-by: Anthea Jiang [anjian@celestica.com](mailto:anjian@celestica.com)

### CODE REVIEW

**Comment by sonoble** [comment]
General comment: 
GitHub is complaining about signatures and the DCO, can you make sure everything is signed off?

**Comment by sonoble** [comment]
This is not building in the default stretch environment:

In file included from /home/ubuntu/OpenNetworkLinux/packages/platforms/celestica/x86-64/silverstone-v2/onlp/builds/x86_64_cel_silverstone_v2/module/src/platform_nonbmc.c:21:0:
/usr/include/linux/i2c.h:68:8: error: redefinition of 'struct i2c_msg'
 struct i2c_msg {
        ^~~~~~~
    Compiling[ release ]: BigList::biglist_last.c
In file included from /home/ubuntu/OpenNetworkLinux/packages/platforms/celestica/x86-64/silverstone-v2/onlp/builds/x86_64_cel_silverstone_v2/module/src/platform_nonbmc.c:20:0:
/usr/include/linux/i2c-dev.h:37:8: note: originally defined here
 struct i2c_msg {
        ^~~~~~~
    Compiling[ release ]: BigList::biglist_copy.c
    Compiling[ release ]: BigList::biglist_prepend_list.c
In file included from /home/ubuntu/OpenNetworkLinux/packages/platforms/celestica/x86-64/silverstone-v2/onlp/builds/x86_64_cel_silverstone_v2/module/src/platform_nonbmc.c:21:0:
/usr/include/linux/i2c.h:131:7: error: redefinition of 'union i2c_smbus_data'
 union i2c_smbus_data {
       ^~~~~~~~~~~~~~
In file included from /home/ubuntu/OpenNetworkLinux/packages/platforms/celestica/x86-64/silverstone-v2/onlp/builds/x86_64_cel_silverstone_v2/module/src/platform_nonbmc.c:20:0:
/usr/include/linux/i2c-dev.h:89:7: note: originally defined here
 union i2c_smbus_data {
       ^~~~~~~~~~~~~~

**Comment by ingridcelestica** [comment]
> General comment: GitHub is complaining about signatures and the DCO, can you make sure everything is signed off?

Yes. Thank you for the information. I have signed off the commits.

**Comment by ingridcelestica** [comment]
> This is not building in the default stretch environment:
> 
> In file included from /home/ubuntu/OpenNetworkLinux/packages/platforms/celestica/x86-64/silverstone-v2/onlp/builds/x86_64_cel_silverstone_v2/module/src/platform_nonbmc.c:21:0: /usr/include/linux/i2c.h:68:8: error: redefinition of 'struct i2c_msg' struct i2c_msg { ^~~~~~~ Compiling[ release ]: BigList::biglist_last.c In file included from /home/ubuntu/OpenNetworkLinux/packages/platforms/celestica/x86-64/silverstone-v2/onlp/builds/x86_64_cel_silverstone_v2/module/src/platform_nonbmc.c:20:0: /usr/include/linux/i2c-dev.h:37:8: note: originally defined here struct i2c_msg { ^~~~~~~ Compiling[ release ]: BigList::biglist_copy.c Compiling[ release ]: BigList::biglist_prepend_list.c In file included from /home/ubuntu/OpenNetworkLinux/packages/platforms/celestica/x86-64/silverstone-v2/onlp/builds/x86_64_cel_silverstone_v2/module/src/platform_nonbmc.c:21:0: /usr/include/linux/i2c.h:131:7: error: redefinition of 'union i2c_smbus_data' union i2c_smbus_data { ^~~~~~~~~~~~~~ In file included from /home/ubuntu/OpenNetworkLinux/packages/platforms/celestica/x86-64/silverstone-v2/onlp/builds/x86_64_cel_silverstone_v2/module/src/platform_nonbmc.c:20:0: /usr/include/linux/i2c-dev.h:89:7: note: originally defined here union i2c_smbus_data { ^~~~~~~~~~~~~~

Yes, @sonoble  I saw there are some issues have this redefinition problem either. I referred one closed issue and verified the onlp which worked well. Please check. Thank you.

**Comment by ingridcelestica** [comment]
@sonoble Hi Steven. Any comment from you?

**Comment by sonoble** [comment]
Hello,
Yes it is being reviewed, it's a very large diff, 30k lines, so it takes time.  While I am able to build and run it now, I am still waiting for confirmation that it works on some platforms that I don't have direct access to.

**Comment by ingridcelestica** [comment]
Got it. I will wait for it. Thank you.

**Review by sonoble — APPROVED** [review]

**Pull request merged**
