### PR TITLE
[Wedge100-32x] Add new platform x86-64-accton-wedge100-32x

### PR DESCRIPTION
**Pull request by brandonchuang**

### CODE REVIEW

**Comment by sonoble** [comment]
Hi Brandon, thank you for the pull! Is this different than the Facebook wedge 100 or can we replace ours with yours for both platforms?

**Comment by brandonchuang** [comment]
Hi @sonoble ,

As I know, the hardware design is the same, but the machine name in ONIE are different.
Here is my ONIE machine.conf for your reference.

ONIE:/ # cat /etc/machine.conf
onie_version=2017.02.00.04-dirty
onie_vendor_id=259
onie_platform=x86_64-accton_wedge100_32x-r0
onie_machine=accton_wedge100_32x
onie_machine_rev=0
onie_arch=x86_64
onie_config_version=1
onie_build_date="2017-04-21T10:43+0800"
onie_partition_type=gpt
onie_kernel_version=4.1.23
onie_firmware=auto
onie_switch_asic=bcm
onie_skip_ethmgmt_macs=no
onie_grub_image_name=grubx64.efi

**Comment by sonoble** [comment]
Hi Brandon,

I am seeing some issues with the code running on a fb w100 with a modified machine.conf to install your code. Is this due to my hardware or do you see this also? (I have been soaking the code for a day or so).

traps: onlp-snmpd[1190] trap divide error ip:7f1b448d057c sp:7f1b440385c0 error:0 in libonlp-x86-64-accton-wedge100-32x.so[7f1b448bc000+29000]
ast-i2c ast-i2c.7: I2C(7) ast_i2c_wait_bus_not_busy slave_op=0 (ctrl=1,cmd=c430000)
ast-i2c ast-i2c.7: I2C(7) bus hang! Master Lock (ctrl=1,cmd=c430000)
ast-i2c ast-i2c.7: I2C(7) bus hang! Master Lock: Recovery Success (ctrl=1,cmd=a060000)
ast-i2c ast-i2c.7: I2C(7) recover completed (ctrl,cmd): before(1,c430000) after(1,a060000)
ast-i2c ast-i2c.7: I2C(7) M|&S disable completed (ctrl,cmd): before(1,a060000) after(0,a060000)
ast-i2c ast-i2c.7: I2C(7) reset completed (ctrl,cmd): before(0,a060000) after(1,a060000)
ast-i2c ast-i2c.7: I2C(7) ast_i2c_wait_bus_not_busy slave_op=0 (ctrl=1,cmd=c430000)
ast-i2c ast-i2c.7: I2C(7) bus hang! Master Lock (ctrl=1,cmd=c430000)
ast-i2c ast-i2c.7: I2C(7) bus hang! Master Lock: Recovery Success (ctrl=1,cmd=a060000)
ast-i2c ast-i2c.7: I2C(7) recover completed (ctrl,cmd): before(1,c430000) after(1,a060000)
ast-i2c ast-i2c.7: I2C(7) M|&S disable completed (ctrl,cmd): before(1,a060000) after(0,a060000)
ast-i2c ast-i2c.7: I2C(7) reset completed (ctrl,cmd): before(0,a060000) after(1,a060000)
ast-i2c ast-i2c.7: I2C(7) ast_i2c_wait_bus_not_busy slave_op=0 (ctrl=1,cmd=c430000)
ast-i2c ast-i2c.7: I2C(7) bus hang! Master Lock (ctrl=1,cmd=c430000)
ast-i2c ast-i2c.7: I2C(7) bus hang! Master Lock: Recovery Success (ctrl=1,cmd=a060000)
ast-i2c ast-i2c.7: I2C(7) recover completed (ctrl,cmd): before(1,c430000) after(1,a060000)
ast-i2c ast-i2c.7: I2C(7) M|&S disable completed (ctrl,cmd): before(1,a060000) after(0,a060000)
ast-i2c ast-i2c.7: I2C(7) reset completed (ctrl,cmd): before(0,a060000) after(1,a060000)

**Comment by brandonchuang** [comment]
Hi @sonoble,
I tried to replicate the issue, and sometimes the message will show up without typing any command.
I am not sure where does the log come from and what happen to bus 7 so far.
I will keep looking into the issue later.
Thanks.

**Comment by sonoble** [comment]
Thanks Brandon.  That is what is happening here, I just have a terminal open to the console, no commands are sent and I see the messages.

**Comment by brandonchuang** [comment]
Hi @sonoble ,
I will send the pull request again if I found the root cause.
Thanks.

**Pull request closed without merging**
