### PR TITLE
Fix as7512 32x operation

### PR DESCRIPTION
**Pull request by pkarashchenko**

### CODE REVIEW

**Comment by jnealtowns** [comment]
Thank you @pkarashchenko for your submission. 
@Lewis-Kang can you review?

**Comment by Lewis-Kang** [comment]
@jnealtowns, I checked with onlp driver developer @brandonchuang who said he will get the new AS7512 HW tomorrow (4/7). @brandonchuang will help verify and review. Thanks.

@pkarashchenko, thanks!

**Comment by brandonchuang** [comment]
Hi,

It looks fine with me.
The output is listed below:

root@localhost:~# onlpdump
   System Information: = {
       Product Name: 7512-32X-O-AC-F
       Part Number: FP3ZZ7632012A
       Serial Number: 751232X1634007
       MAC: 8c:ea:1b:18:64:47
       MAC Range: 130
       Manufacturer: Accton
       Manufacture Date: 08/17/2016 23:20:15
       Vendor: Edgecore
       Platform Name: x86_64-accton_as7512_32x-r0
       Label Revision: R01A
       Country Code: TW
       Diag Version: 1.0.0.1
       ONIE Version: 2016.05.00.02
   }
   thermal @ 1 = {
       Description: Chassis Thermal Sensor 1
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
       Temperature: 33000
       thresholds = {
           Warning: 45000
           Error: 55000
           Shutdown: 60000
       }
   }
   thermal @ 2 = {
       Description: Chassis Thermal Sensor 2
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
       Temperature: 32000
       thresholds = {
           Warning: 45000
           Error: 55000
           Shutdown: 60000
       }
   }
   thermal @ 3 = {
       Description: Chassis Thermal Sensor 3
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
       Temperature: 29500
       thresholds = {
           Warning: 45000
           Error: 55000
           Shutdown: 60000
       }
   }
   thermal @ 4 = {
       Description: Chassis Thermal Sensor 4
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
       Temperature: 35250
       thresholds = {
           Warning: 45000
           Error: 55000
           Shutdown: 60000
       }
   }
   thermal @ 5 = {
       Description: Chassis Thermal Sensor 5
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
       Temperature: 46875
       thresholds = {
           Warning: 45000
           Error: 55000
           Shutdown: 60000
       }
   }
   led @ 1 = {
       Description: Chassis LED 1 (DIAG LED)
       Status: 0x00000005 [ PRESENT,ON ]
       Caps:   0x00011401 [ ON_OFF,RED,ORANGE,GREEN ]
       Mode: GREEN
       Char:
   }
   led @ 2 = {
       Description: Chassis LED 2 (LOC LED)
       Status: 0x00000005 [ PRESENT,ON ]
       Caps:   0x00040001 [ ON_OFF,BLUE ]
       Mode: BLUE
       Char:
   }
   led @ 3 = {
       Description: Chassis LED 3 (FAN LED)
       Status: 0x00000005 [ PRESENT,ON ]
       Caps:   0x00400000 [ AUTO ]
       Mode: AUTO
       Char:
   }
   led @ 4 = {
       Description: Chassis LED 4 (PSU1 LED)
       Status: 0x00000005 [ PRESENT,ON ]
       Caps:   0x00400000 [ AUTO ]
       Mode: AUTO
       Char:
   }
   led @ 5 = {
       Description: Chassis LED 4 (PSU2 LED)
       Status: 0x00000005 [ PRESENT,ON ]
       Caps:   0x00400000 [ AUTO ]
       Mode: AUTO
       Char:
   }
   psu @ 1 = {
       Description: PSU-1
       Model:  YM-2651Y

       SN:     NULL
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00000151 [ AC,VOUT,IOUT,POUT ]
       Vin:    0
       Vout:   12062
       Iin:    0
       Iout:   5898
       Pin:    0
       Pout:   70000
       fan @ 7 = {
           Description: Chassis PSU-1 Fan 1
           Status: 0x00000009 [ PRESENT,F2B ]
           Caps:   0x00000038 [ SET_PERCENTAGE,GET_RPM,GET_PERCENTAGE ]
           RPM:    5000
           Per:    19
           Model:  NULL
           SN:     NULL
       }
       thermal @ 6 = {
           Description: PSU-1 Thermal Sensor 1
           Status: 0x00000001 [ PRESENT ]
           Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
           Temperature: 25000
           thresholds = {
               Warning: 45000
               Error: 55000
               Shutdown: 60000
           }
       }
   }
   psu @ 2 = {
       Description: PSU-2
       Model:  YM-2651Y

       SN:     NULL
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00000151 [ AC,VOUT,IOUT,POUT ]
       Vin:    0
       Vout:   12031
       Iin:    0
       Iout:   4796
       Pin:    0
       Pout:   58000
       fan @ 8 = {
           Description: Chassis PSU-2 Fan 1
           Status: 0x00000009 [ PRESENT,F2B ]
           Caps:   0x00000038 [ SET_PERCENTAGE,GET_RPM,GET_PERCENTAGE ]
           RPM:    5000
           Per:    19
           Model:  NULL
           SN:     NULL
       }
       thermal @ 7 = {
           Description: PSU-2 Thermal Sensor 1
           Status: 0x00000001 [ PRESENT ]
           Caps:   0x0000000f [ GET_TEMPERATURE,GET_WARNING_THRESHOLD,GET_ERROR_THRESHOLD,GET_SHUTDOWN_THRESHOLD ]
           Temperature: 30000
           thresholds = {
               Warning: 45000
               Error: 55000
               Shutdown: 60000
           }
       }
   }
   fan @ 1 = {
       Description: Chassis Fan 1
       Status: 0x00000009 [ PRESENT,F2B ]
       Caps:   0x00000038 [ SET_PERCENTAGE,GET_RPM,GET_PERCENTAGE ]
       RPM:    2000
       Per:    11
       Model:  NULL
       SN:     NULL
   }
   fan @ 2 = {
       Description: Chassis Fan 2
       Status: 0x00000009 [ PRESENT,F2B ]
       Caps:   0x00000038 [ SET_PERCENTAGE,GET_RPM,GET_PERCENTAGE ]
       RPM:    4400
       Per:    24
       Model:  NULL
       SN:     NULL
   }
   fan @ 3 = {
       Description: Chassis Fan 3
       Status: 0x00000009 [ PRESENT,F2B ]
       Caps:   0x00000038 [ SET_PERCENTAGE,GET_RPM,GET_PERCENTAGE ]
       RPM:    6600
       Per:    36
       Model:  NULL
       SN:     NULL
   }
   fan @ 4 = {
       Description: Chassis Fan 4
       Status: 0x00000009 [ PRESENT,F2B ]
       Caps:   0x00000038 [ SET_PERCENTAGE,GET_RPM,GET_PERCENTAGE ]
       RPM:    9100
       Per:    50
       Model:  NULL
       SN:     NULL
   }
   fan @ 5 = {
       Description: Chassis Fan 5
       Status: 0x00000009 [ PRESENT,F2B ]
       Caps:   0x00000038 [ SET_PERCENTAGE,GET_RPM,GET_PERCENTAGE ]
       RPM:    11300
       Per:    62
       Model:  NULL
       SN:     NULL
   }
   fan @ 6 = {
       Description: Chassis Fan 6
       Status: 0x00000009 [ PRESENT,F2B ]
       Caps:   0x00000038 [ SET_PERCENTAGE,GET_RPM,GET_PERCENTAGE ]
       RPM:    13200
       Per:    73
       Model:  NULL
       SN:     NULL
   }

SFPs:
  Presence Bitmap: 0
  RX_LOS Bitmap: 0

Port 00: Present, Status = 0x00000000
eeprom:
  0000: 0d 00 06 00 00 00 00 00 00 00 00 00 00 00 00 00
  0010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0050: 00 00 00 00 00 00 01 00 00 00 00 00 00 00 00 00
  0060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00
  0080: 0d 00 23 00 00 00 00 00 00 00 00 00 67 00 00 00
  0090: 00 00 00 80 41 6d 70 68 65 6e 6f 6c 20 20 20 20
  00a0: 20 20 20 20 00 78 a7 14 35 39 39 39 34 30 30 31
  00b0: 35 20 20 20 20 20 20 20 4a 20 00 00 00 00 46 e8
  00c0: 00 00 00 00 41 50 46 31 34 31 39 30 31 35 33 50
  00d0: 31 36 20 20 31 34 30 35 32 32 20 20 00 00 00 d4
  00e0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
  00f0: ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff ff
Port 01: Missing.
Port 02: Missing.
Port 03: Missing.
Port 04: Missing.
Port 05: Missing.
Port 06: Missing.
Port 07: Missing.
Port 08: Missing.
Port 09: Missing.
Port 10: Missing.
Port 11: Missing.
Port 12: Missing.
Port 13: Missing.
Port 14: Missing.
Port 15: Missing.
Port 16: Missing.
Port 17: Missing.
Port 18: Missing.
Port 19: Missing.
Port 20: Missing.
Port 21: Missing.
Port 22: Missing.
Port 23: Missing.
Port 24: Missing.
Port 25: Missing.
Port 26: Missing.
Port 27: Missing.
Port 28: Missing.
Port 29: Missing.
Port 30: Missing.
Port 31: Missing.
root@localhost:~#

**Comment by pkarashchenko** [comment]
@jnealtowns seems that test are ok. Can we merge the changes?

**Comment by jnealtowns** [comment]
Thank you @pkarashchenko  @brandonchuang  @Lewis-Kang . 
We will merge the change.

**Pull request merged**
