### PR TITLE
Support Netberg Platform

### PR DESCRIPTION
**Pull request by raymondhuey**
Support Aurora 620 and Aurora 720

### CODE REVIEW

**Comment by jnealtowns** [comment]
@raymondhuey Before we review your pull request I have a quick comment. 
The platform identifiers used for your platforms are not really compliant with the ONIE specification as they do not include your vendor name. I would expect the platforms to be identified as x86_64-netberg_hurican-r0. Can you comment on whether you expect to use a compliant identifier? Here is the relevant specification:
https://github.com/opencomputeproject/onie/wiki/Design-Spec-SW-Image-Discovery#platform-name-and-identification

**Comment by raymondhuey** [comment]
@jnealtowns Because the ONIE on Netberg's platform is used for multiple vendor and multiple platforms(Aurora 620 and Aurora 720), we use a common identifier "x86_64-huracan_rangeley-r0" to recognize those platforms. And we don't want to maintain the same ONIE code for different vendors and different platforms.

**Comment by sonoble** [comment]
Hi Raymond,

Can you point us to the release version of ONIE with your systems in it?  The latest code push, 2017-05 does not appear to have the huracan systems in it.

**Comment by raymondhuey** [comment]
@sonoble The version of ONIE with this system is 2015.11 and we didn't commit huracan system to the public ONIE.

**Pull request closed without merging**
