### PR TITLE
[Edgecore][as7946-74xkb] Upgrade kernel to 5.4

### PR DESCRIPTION
**Pull request by JakeLin-EC**
1. Enable the IPMI related configuration. (Refer to the original kernel 4.19)
2. Enable coretemp config to make onlpdump work as kernel 4.19.
3. Enable pca954x config to make i2c mux work as kernel 4.19
4. Modify ipmi_user_t in drivers to match kernel 5.4 data type.

Signed-off-by: Jake Lin <jake_lin@edge-core.com>

### CODE REVIEW

**Comment by paulmenzel** [comment]
Thank you for the patch. Could you please split it into five commits, and also add a note, why you switch from 4.19 to 5.4, and if you noticed any differences.

**Comment by JakeLin-EC** [comment]
Thank for your 
I will split it to five commit:
1. Upgrade as7946-74xkb kernel version to 5.4
2. Enable the IPMI related configuration. (Refer to the original kernel 4.19)
3. Modify ipmi_user_t in drivers to match kernel 5.4 data type
4. Enable coretemp config to make onlpdump work as kernel 4.19.
5. Enable pca954x config to make i2c mux work as kernel 4.19

The reason we upgrade kernel to 5.4 is customer's requirement, and our kernel version is based on 5.4 for new switch in future.

**Comment by JakeLin-EC** [comment]
Hi @paulmenzel ,
I have already split it to 5 commits.

**Comment by paulmenzel** [comment]
Awesome. Two more nits:

1.  In each commit message, please add a blank line between the summary and the body.
2.  Order `[as7946-74xkb] Upgrade kernel to 5.4` on top of the series (`git rebase -i …`).

**Comment by JakeLin-EC** [comment]
Hi @paulmenzel ,

1. I added a blank line to all commits between the summary and body.

1. I reorderd the commit `[as7946-74xkb] Upgrade kernel to 5.4` on top of the series.

**Review by sonoble — APPROVED** [review]
Image built and confirmed good.

**Pull request merged**
