### PR TITLE
Add ppc64 arch and t2080 platform support

### PR DESCRIPTION
**Pull request by shengzhou**

### CODE REVIEW

**Comment by bsn-abat** [comment]
Can one of the admins verify this patch?

**Comment by jnealtowns** [comment]
@shengzhou We can't accept this patch as-is. The modifications for the buildroot build and the toolchain issues would need to be resolved. 

Since we don't have a PPC64 userland available for ONL the only thing this patch will allow would be building and running a 64bit kernel with a 32bit userland. As a result I'm wondering why you didn't continue to use the 32bit PPC loader build instead of creating a new 64bit version. Are there systems you plan to deploy in this way?

I also think we would prefer your vendor name to be NXP rather than Freescale. 

It would be easier for us to support this effort if NXP donated an T2080RDB system to the ONL qualification lab.

**Comment by shengzhou** [comment]
@jnealtowns  I have updated patch set to latest base(May 18), now both builds and running ONL on t2080rdb are verified successfully.   I have rename vendor name from Freescale to NXP in the patch set.
As T2080 targets on 64b PPC, ppc 32b kernel on T2080 SoC (E6500  PPC64 core)  may cause exception with full filesystem, so we have to use ppc64 kernel for t2080, both 32b userland and 64b userland can work with this ppc64 kernel, I will add 64b userland support for t2080 after I finish arm64 arch on LS2080 platform with high priority.   Could you please add debian8 arm64 toolchain into ONL?

**Comment by shengzhou** [comment]
Hi @jnealtowns  
With regard to "It would be easier for us to support this effort if NXP donated an T2080RDB system to the ONL qualification lab",   NXP will donate T2080RDB (a reference design board hosting ppc64 big endian SoC, supporting multiple 1G and 10G ethernet ports, without data plane ASIC, expect as control plane for switch) and LS2080RDB (arm64 little endian SoC) to ONL qualification lab, how many boards would be proper for the support of ONL qualification lab?

**Comment by sonoble** [comment]
@jnealtowns Can you confirm that this patch (still needs to be rebased) would be acceptable or are there still issues that need to be resolved?

**Comment by shengzhou** [comment]
I will rebase and update the patch set in another pull reqest, so close this one.

**Pull request closed without merging**
