### PR TITLE
[as4610-30/as4610-54] Add device driver and onlp

### PR DESCRIPTION
**Pull request by brandonchuang**
- Add 4610-30 platform environment 
- Add device driver for both 4610-30 and 4610-54
- Add onlp for 4610-30 and 4610-54

### CODE REVIEW

**Comment by bsn-abat** [comment]
Can one of the admins verify this patch?

**Comment by Lewis-Kang** [comment]
Hi BSN staff, 

The HW support list https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/docs/SupportedHardware.md

can add the following when this pull request is merged:
AS4610-54T (OF-DPA, OpenNSL: *** Vendor provided)
AS4610-30P (OF-DPA, OpenNSL: *** Vendor provided)
AS4610-30T (OF-DPA, OpenNSL: *** Vendor provided)

By the way, for already supported platforms AS5812-54T and AS4610-54P, please help add (OF-DPA, OpenNSL: *** Vendor provided) too. Thanks.

**Comment by sonoble** [comment]
Hi Lewis, are these three systems similar (same processor/fans/power?)  We only have one of them, so knowing that we can test on the one is important.

**Comment by Lewis-Kang** [comment]
Hi Steven, 

Those four AS4610 platforms all use BRCM Helix4 ASIC with the same ARM processor inside. But AS4610-54 platforms use Helix4 BCM56340; AS4610-30 platforms use Helix4 BCM56342.

Two of those four platforms with PoE has fans; the other two without PoE has no fans.

Though, the Power modules used by PoE platforms and by non-PoE platforms are different, the methods to access their status are the same.

**Comment by jnealtowns** [comment]
@Lewis-Kang  @brandonchuang 
I am reviewing and testing your pull request. 

The code for the -30 and the -54 modules looks basically the same. It might be better to merge them into one common code module that can handle both platform types (instead of two duplicates). 

The code modules can be merged into a shared module under packages/platforms/accton/armel/src/arm_accton_as4610

The onlp_sysi_platform_get() implementation should return "arm_accton_as4610". This will not match the current platform name, and the upper layer will then call onlp_sysi_platform_set() with the current platform identifier. The new unified module code will then select the -30 or -54 variant based on the received platform identifier. 

This same mechanism is used in the existing 5710 implementation to support both the R0 and the R0B platforms. Here is the relevant code:
https://github.com/opencomputeproject/OpenNetworkLinux/blob/master/packages/platforms/accton/powerpc/powerpc-accton-as5710-54x/onlp/builds/src/module/src/sysi.c#L45

**Comment by Lewis-Kang** [comment]
@jnealtowns Thanks for the review

@brandonchuang @jnealtowns There are two ONIE images for -30 and -54 respectively. if ONL only uses as4610 as the platform name, its ONIE installer script may need to modify to be able to install NOS via ONIE successfully. And, the NOS applications (if not using onlp lib), which originally use /etc/onl/platform to check which platform they are running upon for setting different configurations, have to access CPLD to check the board ID to decide the configurations.

@brandonchuang Any issues for ONLP's peripheral control while single as4610 name is used?

**Comment by jnealtowns** [comment]
@Lewis-Kang No one said anything about changing the platform name.  I am not suggesting that you combine the platform identifiers. ONL will still recognize -30 and -54 as different platforms. This request does not change the platform identification process in any way. 

The suggestion here is to merge the ONLP implementation code modules for both the -30 and the -50 into a single code module for maintenance and avoidance of duplication of effort. 

This new module library: https://github.com/brandonchuang/OpenNetworkLinux/tree/master/packages/platforms/accton/armel/arm-accton-as4610-30/onlp/builds/src/arm_accton_as4610_30

And this new module library:
https://github.com/brandonchuang/OpenNetworkLinux/tree/master/packages/platforms/accton/armel/arm-accton-as4610-54/onlp/builds/src/arm_accton_as4610_54

Are almost identical, and could be shared by the mechanism I described in my suggestion. 
There appear to be only a slight difference between these two libraries to account for the minor difference in the platforms. 

The merged code would be used by the platform shared library built by *both* platforms. As part of the process I described (onlp_sysi_platform_set)

**Comment by Lewis-Kang** [comment]
@jnealtowns sorry for my misunderstanding and thanks.

**Comment by jnealtowns** [comment]
@Lewis-Kang  No apologies necessary :-)

**Comment by brandonchuang** [comment]
@jnealtowns Done to merge AS4610-30 and AS4610-54. If it is ok. please help to accept to push request. Thanks.

**Comment by jnealtowns** [comment]
@brandonchuang This looks mostly good, but the platform configuration packages should not be shared, only the onlp src code. 

Please look at this pull request I've made:
https://github.com/opencomputeproject/OpenNetworkLinux/pull/92

It contains separate platform configuration packages for the AS4610-30 and AS4610-54. There need to be packages matching their platform identifiers, they cannot be shared. 

You will see in the pull request that the ONLP shared library build for both platforms uses the same arm_accton_as4610 source code module. 

This arrangement is the one I was suggesting. If you approve of the arrangement we can merge the existing pull request. If you would like to make further changes I'll leave that up to you.

**Comment by brandonchuang** [comment]
@jnealtowns It is ok for me, please go ahead. Thanks.

**Comment by jnealtowns** [comment]
Superceded by https://github.com/opencomputeproject/OpenNetworkLinux/pull/92

**Pull request closed without merging**
