### PR TITLE
Update __init__.py

### PR DESCRIPTION
**Pull request by balajikp**

### CODE REVIEW

**Comment by brandonchuang** [comment]
May I know why do you need to change this file.
Does the pca954x different from your device?
Which programming guide do you refer to?

Thanks,
Brandon

**Comment by Marc2508** [comment]
On our 5912 we got an error during startup as the address is 0x71 not 0x74:
[27.823460] pca954x 1-0074: probe failed

In addition the (Q)SFPs are connected to another 7 pca954x (in blocks of 8), each with an own address connected to a channel of pca954x on 0x72. So addressing them all via 0x77 is not working.

**Comment by brandonchuang** [comment]
Could you provide me detailed H/W information?
Like H/W revision or anything else for me?
Thanks.

**Comment by Marc2508** [comment]
This is what we get with onlpdump:

Product Name: 5912-54X-O-AC-F
Part Number: FP3ZZ5654000A
Manufacturer: Accton
Manufacture Date: 06/06/2016 12:00:00
Vendor: Edgecore
Platform Name: x86_64-accton_as5912_54x-r0

**Comment by brandonchuang** [comment]
It looks like your H/W revision is R0A.
This revision has been phased out and not supported.
Please help close the pull request and keep the changes at your local.
Thanks.

**Pull request closed without merging**
