### PR TITLE
Add new platform Inventec d5052

### PR DESCRIPTION
**Pull request by qipingf**
1. Add platform support for Inventec d5052 switch
  2. Configure ISMT as a module

### CODE REVIEW

**Comment by jnealtowns** [comment]
@qipingf We can't change the ISMT driver to a module in the 3.16 kernel configuration because too many other platforms depend on it. 

Can I suggest that you instead move to the 4.14-LTS kernel?
If not and you must stay on 3.16 I will advise how to solve your problem.

**Comment by qipingf** [comment]
Hi Jeffrey,
Thank you very much for your comment.
I saw ISMT driver was configured as a module in ONL kernel 4.9-LTS. 
 ./packages/base/any/kernels/4.9-lts/configs/x86_64-all/x86_64-all.config:CONFIG_I2C_ISMT=m

If it can not be done in 3.16-LTS kernel, could you please let me know how to solve this problem in ONL ? We prefer to stay on 3.16 currently.

Thanks,

**Comment by jnealtowns** [comment]
@qipingf If you must remain on 3.16 then you can add the following kernel argument to your platform-config yaml file:
 i2c-ismt.enable=0

This will disable the loading of the driver in the kernel.

**Comment by qipingf** [comment]
@jnealtowns  Thank you for your advice.  I discard CONFIG_I2C_ISMT=m configuration and add i2c-ismt.enable=0 in platform-config  .yml file, the conflict issue is solved. It works fine.

**Pull request merged**
