### PR TITLE
[Celestica/belgite] Add platform belgite

### PR DESCRIPTION
**Pull request by nicwu-cel**
- CPU: Intel Denverton
- MAC: Broadcom BCM56277
- Network: 48x10/100/1000M RJ45 ports and 8xSFP+

Signed-off-by: Nicholas Wu <nicwu@celestica.com>
Signed-off-by: Pradchaya Phucharoen <pphuchar@celestica.com>
Signed-off-by: Srikanth Krishnamachary <srikanth@celestica.com>
Signed-off-by: Ramar N <nramar@celestica.com>

### CODE REVIEW

**Comment by nicwu-cel** [comment]
@paulmenzel

I would appreciate it if you could help review this pull request. 

Looking forward to hearing from you soon.

Best Regards!

**Comment by paulmenzel** [comment]
Sorry, it’s my understanding that no vendor(s) stepped up to take over maintenance of ONL, so it’s currently dead. Dropping new boards is irresponsible in the current state, so I won’t be able to help.

Maybe @sonoble has some more insight.

I am sorry about that.

**Comment by nicwu-cel** [comment]
Thanks @paulmenzel.

Hi @sonoble, do you have any idea about this?

**Comment by nicwu-cel** [comment]
Hi @sonoble, do you have any idea about this?

**Comment by sonoble** [comment]
I attempted to patch it in and build but there were errors, I sent them to Jeff and asked him to forward.

INFO:onlpm:Rebuilding onlp-x86-64-cel-belgite-r0:amd64...
make[4]: warning: -jN forced in submake: disabling jobserver mode.
   Compiling[ release ]: aim::aim_valgrind.c
   Compiling[ release ]: aim::aim_pvs_file.c
   Compiling[ release ]: aim::aim_pvs.c
   Compiling[ release ]: aim::aim_string.c
   Compiling[ release ]: aim::aim_log.c
   Compiling[ release ]: aim::aim_enums.c
   Compiling[ release ]: aim::aim_memory.c
   Compiling[ release ]: aim::aim_printf.c
   Compiling[ release ]: aim::aim_daemon.c
   Compiling[ release ]: aim::aim_rl.c
   Compiling[ release ]: aim::aim_module.c
   Compiling[ release ]: aim::aim_pvs_buffer.c
   Compiling[ release ]: aim::aim_error.c
   Compiling[ release ]: aim::aim_modules_init.c
   Compiling[ release ]: aim::aim_config.c
   Compiling[ release ]: aim::aim_datatypes.c
   Compiling[ release ]: aim::aim_object.c
   Compiling[ release ]: aim::aim_pvs_syslog.c
   Compiling[ release ]: aim::aim_log_handler.c
   Compiling[ release ]: aim::aim_bitmap.c
   Compiling[ release ]: aim::aim_map.c
   Compiling[ release ]: AIM_posix::aim_thread_posix.c
   Compiling[ release ]: aim::aim_sparse.c
   Compiling[ release ]: AIM_posix::aim_time_posix.c
   Compiling[ release ]: IOF::iof.c
   Compiling[ release ]: AIM_posix::aim_sleep_posix.c
   Compiling[ release ]: IOF::iof_config.c
   Compiling[ release ]: AIM_posix::aim_sem_posix.c
   Compiling[ release ]: IOF::iof_log.c
   Compiling[ release ]: onlp::onlp_json.c
   Compiling[ release ]: onlp::onlp_util.c
   Compiling[ release ]: onlp::onlp_log.c
   Compiling[ release ]: IOF::iof_module.c
   Compiling[ release ]: onlp::sfp.c
   Compiling[ release ]: onlp::onlp_enums.c
   Compiling[ release ]: onlp::onlp_config.c
   Compiling[ release ]: onlp::thermal.c
   Compiling[ release ]: onlp::onlp.c
   Compiling[ release ]: onlp::onlp_module.c
   Compiling[ release ]: onlp::onlp_ucli.c
   Compiling[ release ]: onlp::led.c
   Compiling[ release ]: onlp::psu.c
   Compiling[ release ]: onlp::platform_manager.c
   Compiling[ release ]: onlp::fan.c
   Compiling[ release ]: onlp::sys.c
   Compiling[ release ]: onlp::oids.c
   Compiling[ release ]: onlplib::sfp.c
   Compiling[ release ]: onlp::onlp_locks.c
   Compiling[ release ]: onlplib::onie.c
   Compiling[ release ]: onlp::onlp_main.c
   Compiling[ release ]: onlp::platform_dump.c
   Compiling[ release ]: onlplib::onlplib_log.c
   Compiling[ release ]: onlplib::file_uds.c
   Compiling[ release ]: onlplib::onlplib_enums.c
   Compiling[ release ]: onlplib::onlplib_module.c
   Compiling[ release ]: onlplib::pi.c
   Compiling[ release ]: onlplib::crc32.c
   Compiling[ release ]: onlplib::thermal.c
   Compiling[ release ]: onlplib::onlplib_config.c
   Compiling[ release ]: onlplib::gpio.c
   Compiling[ release ]: onlplib::file.c
   Compiling[ release ]: x86_64_cel_belgite::platform.c
   Compiling[ release ]: onlplib::mmap.c
   Compiling[ release ]: onlplib::shlocks.c
   Compiling[ release ]: x86_64_cel_belgite::sfpi.c
   Compiling[ release ]: onlplib::i2c.c
   Compiling[ release ]: x86_64_cel_belgite::x86_64_cel_belgite_ucli.c
   Compiling[ release ]: x86_64_cel_belgite::thermali.c
   Compiling[ release ]: x86_64_cel_belgite::psui.c
   Compiling[ release ]: x86_64_cel_belgite::ledi.c
   Compiling[ release ]: x86_64_cel_belgite::sysi.c
   Compiling[ release ]: x86_64_cel_belgite::fani.c
   Compiling[ release ]: x86_64_cel_belgite::x86_64_cel_belgite_log.c
   Compiling[ release ]: x86_64_cel_belgite::x86_64_cel_belgite_enums.c
   Compiling[ release ]: x86_64_cel_belgite::x86_64_cel_belgite_module.c
   Compiling[ release ]: x86_64_cel_belgite::x86_64_cel_belgite_config.c
   Compiling[ release ]: sff::sff_module.c
In file included from /workspace/OpenNetworkLinux/packages/platforms/celestica/x86-64/belgite/onlp/builds/x86_64_cel_belgite/module/src/platform.c:21:0:
/usr/include/linux/i2c.h:68:8: error: redefinition of 'struct i2c_msg'
struct i2c_msg {
       ^~~~~~~
In file included from /workspace/OpenNetworkLinux/packages/platforms/celestica/x86-64/belgite/onlp/builds/x86_64_cel_belgite/module/src/platform.c:20:0:
/usr/include/linux/i2c-dev.h:37:8: note: originally defined here
struct i2c_msg {
       ^~~~~~~
In file included from /workspace/OpenNetworkLinux/packages/platforms/celestica/x86-64/belgite/onlp/builds/x86_64_cel_belgite/module/src/platform.c:21:0:
/usr/include/linux/i2c.h:131:7: error: redefinition of 'union i2c_smbus_data'
union i2c_smbus_data {
      ^~~~~~~~~~~~~~
In file included from /workspace/OpenNetworkLinux/packages/platforms/celestica/x86-64/belgite/onlp/builds/x86_64_cel_belgite/module/src/platform.c:20:0:
/usr/include/linux/i2c-dev.h:89:7: note: originally defined here
union i2c_smbus_data {
      ^~~~~~~~~~~~~~
   Compiling[ release ]: sff::sff_log.c
   Compiling[ release ]: sff::dom.c
/workspace/OpenNetworkLinux/sm/infra/builder/unix/toolchains/gcc-local/obj.mk:109: recipe for target 'BUILD/stretch/x86_64-linux-gnu/obj/workspace/OpenNetworkLinux/packages/platforms/celestica/x86-64/belgite/onlp/builds/x86_64_cel_belgite/module/src/platform.o' failed
make[5]: *** [BUILD/stretch/x86_64-linux-gnu/obj/workspace/OpenNetworkLinux/packages/platforms/celestica/x86-64/belgite/onlp/builds/x86_64_cel_belgite/module/src/platform.o] Error 1
make[5]: *** Waiting for unfinished jobs....
   Compiling[ release ]: sff::cmis.c
/workspace/OpenNetworkLinux/make/subdirs.mk:15: recipe for target 'all' failed
make[4]: *** [all] Error 1
Traceback (most recent call last):

**Comment by nicwu-cel** [comment]
Thanks Steven, by the way, could you help to add Jeff to this review? If he has other questions, I can reply here :)

**Comment by nicwu-cel** [comment]
@paulmenzel

**Comment by nicwu-cel** [comment]
Hi Steven, I've pulled the code and built the ONL on my side again, the result was pass.

**Comment by nicwu-cel** [comment]
Hi @sonoble, do you have any idea about this?

**Comment by sonoble** [comment]
Hi sorry for the late reply,

Are you building debian 8 or 9?  I am wondering what the difference is
between our builds.

**Comment by nicwu-cel** [comment]
Hi @sonoble, I used debian 10 to build this platform on my side and there are no errors.

**Comment by nicwu-cel** [comment]
Hi @sonoble, is there any updates about this?

**Comment by nicwu-cel** [comment]
Hi @sonoble, may I know if you have built this PR successfully under debian 10 ?

**Comment by sonoble** [comment]
This is a quagmire as I cannot merge it or it will break the debian 9
builds. I don't have an Allowlist like I do in dentOS so I would need to
implement one that builds systems under the supported debian version.

**Comment by nicwu-cel** [comment]
Hi @sonoble, I've updated the code and built it successfully both in debian 9 and debian 10, could you help to have a check?

**Review by sonoble — APPROVED** [review]

**Comment by nicwu-cel** [comment]
@sonoble, thanks a lot!

**Pull request merged**
