### PR TITLE
Update system eeprom support for Mellanox Platforms

### PR DESCRIPTION
**Pull request by jnealtowns**
Reviewer: @micshy 

Use the new common ONIE syseeprom and machine.conf infrastructure.

    The ONL platform base class supports extracting, parsing, and caching the contents of the ONIE machine.conf file
    and the TLVs in the ONIE system eeprom.

    The mellanox platforms that rely on this information now request it from the common baseclass and use
    the common ONIE JSON parsing infrastructure to populate the onie_info structure in the SYSI implementation.

### CODE REVIEW

**Comment by jnealtowns** [comment]
@micshy  Please review the changes in this pull request and let me know if you approve. It just converts your SYSI implementation to use the common ONIE processing code now available in the platform class and in the onie library.

**Comment by micshy** [comment]
Hi Jeff,

There are 2 small problems:
1st: on msn2700 you remved too much -:), including onlp_sysi_onie_info_get().
2nd: Mellanox has one common ONIE build/version for all platforms.
Thus generic platfrom name is: x86_64-mlnx_x86-r0
At every init onie read onie-syseeprom field "ProductName" and according to it 
configures machine and platforms strings, e.g. x86_64-mlnx_msn2410-r0
Thus I slightly changed onlp_sysi_onie_info_get(), put appropriate platform name
after reading cached json file.
[onlp_sysi_onie_info_get.patch.txt](https://github.com/opencomputeproject/OpenNetworkLinux/files/659418/onlp_sysi_onie_info_get.patch.txt)

Thanks,
   Michael.

**Comment by jnealtowns** [comment]
@micshy  Well thats embarrassing - I built and tested all three platforms. Accidental emacs-yank-and-save.

**Comment by jnealtowns** [comment]
Fixed in https://github.com/opencomputeproject/OpenNetworkLinux/commit/2449ac19c5ad68f106261bae7a5edd990647efc8

**Pull request merged**
