### PR TITLE
[as4610-54t] Support PSU YM-1151F

### PR DESCRIPTION
**Pull request by WillyLiu-EC**

### CODE REVIEW

**Comment by paulmenzel** [comment]
Thank you for the patch.

> Signed-off-by: WillyLiu-EC <willy_liu@edge-core.com>

Can you please use *Willy Liu* as the name?

    $ git config --global user.name "Willy Liu"
    $ git commit --amend -s --author="Willy Liu <willy_liu@edge-core.com>"

Also, it’d be great if you extended the commit message. Maybe:

> PSU YM-1151F can be supported by the existing code, so just make the new model name known.

**Comment by WillyLiu-EC** [comment]
We add the description you suggest and modify name

**Comment by paulmenzel** [comment]
Awesome. Thank you. Two more nits:

1.  Please add a blank line before the Signed-off-by line.
2.  Please also update the name in the merge/pull request description (or just delete it, as all the information is in the commit message).

**Comment by WillyLiu-EC** [comment]
> Awesome. Thank you. Two more nits:
> 
> 1. Please add a blank line before the Signed-off-by line.
=> Edited
> 2. Please also update the name in the merge/pull request description (or just delete it, as all the information is in the commit message).
=> Deleted

**Comment by sonoble** [comment]
Hello,

Please correct the conflicting file and update the pull request so I can merge it.

**Comment by WillyLiu-EC** [comment]
> Hello,
> 
> Please correct the conflicting file and update the pull request so I can merge it.


Hi, we update the pull request to fix the conflicting. Please check it

**Comment by sonoble** [comment]
Hi, Applying the previous patch #873 blocked this patch, can you confirm and fix?

**Comment by WillyLiu-EC** [comment]
> Hi, Applying the previous patch #873 blocked this patch, can you confirm and fix?

Hi, We already modify and confirm the conflicts. Please check it again.

**Pull request merged**
