### PR TITLE
adding Jeff's changes

### PR DESCRIPTION
**Pull request by rohitmalaga**
@capveg Kindly merge Jeff's suggested changes

### CODE REVIEW

**Comment by capveg** [comment]
@rohitmalaga Can you refactor these changes?  They conflict with the patches I had to throw in over the weekend.

**Comment by rohitmalaga** [comment]
@capveg @jnealtowns @sonoble 

Kindly review the changes, I have merged the changes from master repo and also included the Jeff's suggested changes. Renamed the supported field to identified.

**Comment by capveg** [comment]
@jnealtowns : @rohitmalaga has implemented the change I think you suggested to change sff.supported to sff.identified in ONLP itself.  Did you mean to suggest that change for now or is there upstream code that will break based on the rename?  We'll hold to hear your reply.

**Comment by sonoble** [comment]
Can one of the admins verify this patch?

**Comment by jnealtowns** [comment]
@capveg  @rohitmalaga We can't actually change the name without breaking other stuff. I was only pointing out the poor choice of name which caused the initial confusion. That part of this pull request should be reverted.

**Pull request closed without merging**
