### PR TITLE
as7716-32x: fix ma1 linkup issue and port onlp driver from ONL1.0

### PR DESCRIPTION
**Pull request by Lewis-Kang**

### CODE REVIEW

**Comment by sonoble** [comment]
Hi Lewis, 

Did you come up with a plan on how to avoid any issues with the patch interfering with other systems or did you determine that it will not?

**Comment by Lewis-Kang** [comment]
Hi Steven,

This pull request has the related patched code  executed on as7716 only

**Comment by capveg** [comment]
Lewis: can you clarify this?  We ship one kernel that is shared across all
of the boxes, so a patch that only works on one switch is something that is
hard for us to use.   Is there another way of factoring the code to make it
work across all boxes?

- Rob
.

**Comment by jnealtowns** [comment]
@capveg  The patch itself checks to see if its running on a 7716.

**Comment by sonoble** [comment]
I am building now and will test on a few platforms.

**Comment by sonoble** [comment]
I applied this patch and built the installer, it is not working on the 7716 we have in the lab.  Same issue as before; port is there but no traffic

Untracked files:
  (use "git add <file>..." to include in what will be committed)
        packages/base/any/kernels/3.2.65-1+deb7u2/patches/driver-broadcom-tigon3.patch
        packages/base/any/kernels/3.2.65-1+deb7u2/patches/mgmt-port-init-config.patch
        packages/base/any/kernels/3.2.65-1+deb7u2/patches/platform-accton-as7716_32x-device-drivers.patch

tail -3 packages/base/any/kernels/3.2.65-1+deb7u2/patches/series
platform-accton-as7716_32x-device-drivers.patch
driver-broadcom-tigon3.patch
mgmt-port-init-config.patch

**Comment by Lewis-Kang** [comment]
Hi Steven,

Could you show me the output of the following command?

dmidecode -t 1

**Comment by sonoble** [comment]
root@localhost:~# dmidecode -t 1
# dmidecode 2.11
SMBIOS 2.8 present.
# SMBIOS implementations newer than version 2.7 are not
# fully supported by this version of dmidecode.

Handle 0x0001, DMI type 1, 27 bytes
System Information
        Manufacturer: To be filled by O.E.M.
        Product Name: AS7716-32X
        Version: R0CA
        Serial Number: 771632X1548004
        UUID: 03000200-0400-0500-0006-000700080009
        Wake-up Type: Power Switch
        SKU Number: 1
        Family: AS7716-32X

**Comment by Lewis-Kang** [comment]
Hi Steven,

The Manufacturer needs to be "Accton".
Thanks.

Hi Jeff,

I would suggest we change the platform check API only matching Product Name (currently, it also matches Manufacturer). How do you think?

**Comment by Lewis-Kang** [comment]
Hi Steven,

If you remove the following line in kernel driver drivers/hwmon/accton_i2c_cpld.c
	DMI_MATCH(DMI_SYS_VENDOR, "Accton"),

it is supposed to work.

You can give it a try.

Thanks.

**Comment by sonoble** [comment]
I removed the check for Accton and left the one for AS7716 and now the system sees the mgmt port.. (we think alike! :)

pcieport 0000:00:1c.0: ma1: Link is up at 1000 Mbps, full duplex

**Comment by sonoble** [comment]
Can one of the admins verify this patch?

**Comment by capveg** [comment]
@sonoble Is there a new patch?  I thought Lewis asked you to change something but I don't see new code here.

**Comment by sonoble** [comment]
Sorry, that was my pull request test bot asking.  I have modified code, the question was to @jnealtowns if we should just use the AS7716 platform identifier and leave out Accton.  I have confirmed that it works on the 7716, I have not done testing with the other platforms yet, but it seems like it would not cause issues.

**Comment by jnealtowns** [comment]
@Lewis-Kang is this the production BIOS on the AS7716?

**Comment by Lewis-Kang** [comment]
Jeff,

Let me check with PLs here first. Today, I was told baseboard manufacturer was set "Accton", but system manufacturer was not set in production for our data center switches(e.g. AS5712, AS6712,...). If it is true, ONLP driver should not work on those switches too. But I have never heard such issue on AS5712/AS6712,..etc. So it's weird to me. We need to be sure what we set on production BIOS first. Maybe we should use baseboard vendor instead of system vendor since we are sure baseboard vendor is always set in production. Stay tuned, I will let you know. Thanks.

**Comment by sonoble** [comment]
I confirmed that the kernel with DMI_MATCH(DMI_SYS_VENDOR, "Accton") code removed boots on the 5712 and that the ethernet is available.

**Comment by Lewis-Kang** [comment]
@jnealtowns @sonoble 

Our manufacturers do not set System Manufacturer (SM) intentionally. I guess some versions of BIOS writing tools may set it internally from the first-time Baseboard Manufacturer (BM) setting. 

So, we want to use Baseboard Manufacturer (BM) instead of System Manufacturer (SM) and plus Product Name as the condition check to decide which of our switches is currently running. Is it OK for you?

Thanks.

**Comment by jnealtowns** [comment]
Yes.

**Comment by sonoble** [comment]
Do you want to update your pull request or should I push the refactored code I have? Merging the as5512 code made this pull unmergeable.

**Comment by Lewis-Kang** [comment]
Steven,

Does your refactored code include using Baseboard Manufacturer and Product Name as platform matching check?

If you already have the refactored code ready, please help push them in. Thanks in advance!

Steven Noble <notifications@github.com<mailto:notifications@github.com>> 於 2016年4月23日 上午12:21 寫道：


Do you want to update your pull request or should I push the refactored code I have? Merging the as5512 code made this pull unmergeable.

**Comment by sonoble** [comment]
Hi Lewis,

My code only checks for AS7716 but does not seem to work correctly.  It is located at https://github.com/opencomputeproject/OpenNetworkLinux/pull/73 I was using it as a test for the automated build and test integration tool.  Possibly someone can look and see what I missed..

**Comment by Lewis-Kang** [comment]
Hi Steven,

I found you remove SM check for AS7512 -- not AS7716,

**Comment by Lewis-Kang** [comment]
I will update my pull request to resolve conflicts because of that as5512 code merging.

**Comment by sonoble** [comment]
Sounds good.  I am fixing my mistake right now and will check that the kernel works.

**Comment by Lewis-Kang** [comment]
Conflicts solved and use BM. 
Please review and merge to upstream if OK. 
Thanks.

**Comment by sonoble** [comment]
retest this please

**Comment by sonoble** [comment]
Tested on AS5712 and AS7716, any other systems I should check?  I don't have any quanta x86 :(

**Comment by Lewis-Kang** [comment]
Hi Steven,

There is no need to test other Accton switches, since AS7716 is the only switch that uses BRCM MAC's tg3 driver so far. As to other vendors' switches, I have no idea whether they use BRCM MAC's tg3 driver or not on their CPU board.

Thanks.

**Comment by Lewis-Kang** [comment]
Actually, I don't think you need to verify on other vendors' switches either. Because the tg3 driver inside the patch files is got from BRCM's official site. Newer linux kernel versions include that drivers already. And, what we modified will be executed only when it's running on AS7716. So, you can feel safe on merging this pull request to master branch. Or you have any other concerns, please let me know. Thanks.

**Pull request merged**
