### PR TITLE
sfp python binding

### PR DESCRIPTION
**Pull request by rohitmalaga**

### CODE REVIEW

**Comment by bsn-abat** [comment]
Can one of the admins verify this patch?

**Comment by jnealtowns** [comment]
@sonoble  The bsn-abat spam bot is too aggressive.

**Comment by sonoble** [comment]
@jnealtowns it's the same as for any other project, if someone who is not white-listed submits a patch it asks.. I can white list more people so that it auto runs.

**Comment by sonoble** [comment]
add to whitelist

**Comment by sonoble** [comment]
Hi @rohitmalaga the build failed due to issues with the arm version of ONL.  Can you confirm that this builds with the -8 flag (for jessie)?

**Comment by sonoble** [comment]
retest this please

**Comment by sonoble** [comment]
retest this please

**Pull request closed without merging**
