### PR TITLE
Support persistent, directory-based installs

### PR DESCRIPTION
**Pull request by carlroth**
Reviewer: @jnealtowns @sonoble 

- add an 'installed' bootmode that unpacks the squashfs once to a disk partition
- track the unpacked SWI specifier for a TBD SWI upgrade check
- add installer profiles for SWI vs INSTALLED installers

### CODE REVIEW

**Comment by carlroth** [comment]
I'm a little over my head here on fixing the last merge conflict... I resolved the conflict with `packages/platforms-closed` with

`$ git submodule init packages/platforms-closed
$ git add submodules/platforms-closed
`

Some one please check my work on this so that I don't regress this module.

**Comment by sonoble** [comment]
Hi Carl, running git submodule in the directory shows the same hash for platforms-closed as the master has so I don't believe there is an issue.  I am running a Jenkins merge build now.

**Comment by sonoble** [comment]
LGTM will let @jnealtowns look.  Ran Installed and swi installers on 7716 and ly2.

**Comment by carlroth** [comment]
Before we A_C_K this we should discuss some minor warts with this work (and SWI installs in general)

1. the `*::latest` keyword for groveling for SWIs by date is suspect, since the system clock on the switch is probably not correct at the time the first SWI is downloaded
2. the installer tries to extract a `version` file and install it as `/etc/onl/swi_version`. This file is deprecate for current SWIs. Maybe we should be extracting `manifest.json` instead? At a minimum, there is better timestamp info in this file to help address (1)
3. the installer attempts to track the source URL of the SWI and record it in `/.swi` and in `/etc/onl/SWI`. Missing from this scheme is an e.g. `/etc/boot.d/upgrade-swi` script that flags outdated SWI installs
4. As per (3) above, obvs the source URL is kind of hokey; we might also/instead track data from `manifest.json` and also a SWI checksum.

**Comment by jnealtowns** [comment]
@carlroth Lets review on Monday.

**Comment by carlroth** [comment]
There, I cleaned up the handling for SWI version tracking and the 'latest' keyword. We can peel this off to a separate branch if we think the design is half-baked.

**Comment by carlroth** [comment]
ping @jnealtowns @sonoble, the code has evolved a bit and should be re-reviewe

**Comment by jnealtowns** [comment]
I think we should merge. @sonoble does this satisfy all featured needed by the existing (custom) installed users?

**Comment by sonoble** [comment]
Yes, from my testing everything looks ok.  I will put in a pull to correct the wedge init files.

**Pull request merged**
