### PR TITLE
Add three UfiSpace platforms and enable kernel modules in v4.19 kernel config

### PR DESCRIPTION
**Pull request by cytsai0409**
1. Platform S9700-53DX (100G Disaggregated Core and Edge Router)
- CPU: Intel Broadwell-DE 
- MAC: Broadcom BCM88690 
- Network: 40 x 100GE QSFP28 service ports + 13 x 400GE QSFP-DD fabric ports 

2. Platform S9700-23D (400G Disaggregated Core and Edge Router) 
- CPU: Intel Broadwell-DE 
- MAC: Broadcom BCM88690 
- Network: 10 x 400GE QSFP-DD service ports + 13 x 400GE QSFP-DD fabric ports 

3. Platform S9705-48D (400G Disaggregated Fabric Switch) 
- CPU: Intel Broadwell-DE 
- MAC: Broadcom BCM88790 
- Network: 48 x 400GE QSFP-DD fabric ports   

4. Enable kernel modules for jc42 and eMMC in v4.19 kernel config
- Enable JC42 configs to support memory thermal sensor
- Enable MMC configs to support eMMC module 

5. Change variable length to fix buffer-over-flow issue  
- increase variable ipmi_cmd length to fix buffer-over-flow issue 
- align variable cmd_out length with model/serial in onlp_psu_info_t  
- minor code optimization

Signed-off-by: Jason Tsai jason.cy.tsai@ufispace.com

### CODE REVIEW

**Comment by sonoble** [comment]
Hello I will be running this along with the other patch tonight through building to confirm there are no issues.

**Comment by cytsai0409** [comment]
Great and appreciate it.

**Comment by sonoble** [comment]
So the two patches overlap, can you either add the changes from #870 here or the missing items from here there?  Or do we only need one.

**Comment by cytsai0409** [comment]
After internal discussion, please merge this request (#820 ) first and we will re-submit (#870 ) later to fix patch overlap.
Thanks.

**Pull request merged**
